title = "Hyde theme"
description = "A clean blogging theme"

base_url = "https://xgroleau.com"

compile_sass = true
build_search_index = true
generate_feed = true

theme = "hyde"

[markdown]
highlight_code = true

[extra]
hyde_theme = "theme-base-08"
